Exit, if no match is found, and confirm, if user wants to create new session.

diff --git a/tmuxz b/tmuxz
--- a/tmuxz
+++ b/tmuxz
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Exit with message if no variable is given
+# Exit with message, if no variable is given
 if [ -z $1 ]; then
     echo 'Given no session or directory name to attach to.' >&2
     exit 1
@@ -8,6 +8,13 @@ fi
 
 # Query directory path, save directory name and check if session with that name exists
 zoxide_result_path="$( zoxide query $1 )"
+
+# If zoxide query can't find a directory or gets any other error, script exits
+if [ -z $zoxide_result_path ]; then
+    exit 1
+fi
+
+# Save directory name and check if session with that name exists
 zoxide_result="$( echo "${zoxide_result_path}" | awk -F / '{print $NF}' )"
 session_exists="$( tmux ls -F \#S | grep -x "${zoxide_result}" )"
 
@@ -19,12 +26,21 @@ fi
 
 # If no session exists, create one, and if in session already, switch to it.
 if [ -z $session_exists ]; then
-    cd $zoxide_result_path
-    tmux new-session -ds $zoxide_result
-    if [ -z $TMUX ]; then
-        tmux attach-session -t $zoxide_result
+    # Shows the path session would be created in and asks confirmation
+    echo "You are about to open a tmux session in ${zoxide_result_path}."
+    read -p 'Do you want to continue? [Y/n]' -n 1 -r
+    echo
+    if [[ "$REPLY" =~ ^[Yy]$ ]] || [ -z $REPLY ]; then
+        cd $zoxide_result_path
+        tmux new-session -ds $zoxide_result
+        if [ -z $TMUX ]; then
+            tmux attach-session -t $zoxide_result
+        else
+            tmux switch-client -t $zoxide_result
+        fi
     else
-        tmux switch-client -t $zoxide_result
+        echo 'Aborted session creation.'
+        exit 0
     fi
 # If session exists, attach to it, and if in session already, switch to it.
 else
